# Generated by Django 5.2.10 on 2026-04-20 02:13

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="ExpenseCategory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                ("description", models.TextField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("unit_value", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total_value", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Supplier",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                ("tax_id", models.CharField(max_length=20, unique=True)),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.TextField(blank=True, null=True)),
                (
                    "balance",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="SupplierTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("transaction_number", models.CharField(max_length=50)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("description", models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Area",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "budget_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaMonthlyAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                (
                    "amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notes", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="adjustments",
                        to="purchases.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AreaMonthlyLimit",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("year", models.PositiveIntegerField()),
                ("month", models.PositiveIntegerField()),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="monthly_limits",
                        to="purchases.area",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Purchase",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[
                            ("FACTURA", "Factura"),
                            ("BOLETA", "Boleta"),
                            ("RXH", "Recibo por Honorarios"),
                            ("NOTA_VENTA", "Nota de Venta"),
                            ("NOTA_CREDITO", "Nota de Crédito"),
                            ("NOTA_DEBITO", "Nota de Débito"),
                            ("TICKET", "Ticket"),
                            ("RECIBO_DE_SERVICIOS", "Recibo de Servicios"),
                            ("SIN_ESPECIFICAR", "Sin especificar"),
                        ],
                        default="FACTURA",
                        max_length=20,
                    ),
                ),
                ("series", models.CharField(blank=True, max_length=20, null=True)),
                ("number", models.CharField(blank=True, max_length=20, null=True)),
                (
                    "cost_type",
                    models.CharField(
                        choices=[("CF", "Costo Fijo"), ("CV", "Costo Variable")],
                        default="CF",
                        max_length=2,
                        verbose_name="Tipo de Costo",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[("CASH", "Efectivo"), ("TRANSFER", "Transferencia")],
                        default="TRANSFER",
                        max_length=20,
                        verbose_name="Método de Pago",
                    ),
                ),
                ("issue_date", models.DateField()),
                ("due_date", models.DateField(blank=True, null=True)),
                ("registration_date", models.DateTimeField(auto_now_add=True)),
                (
                    "budget_period",
                    models.DateField(
                        default=django.utils.timezone.now,
                        help_text="Mes al que se cargará este gasto en el presupuesto",
                        verbose_name="Periodo de Presupuesto",
                    ),
                ),
                (
                    "specific_concept",
                    models.CharField(blank=True, max_length=200, null=True),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PEN", "Soles (S/)"), ("USD", "Dólares ($)")],
                        default="PEN",
                        max_length=3,
                        verbose_name="Moneda",
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(
                        decimal_places=3,
                        default=1.0,
                        max_digits=6,
                        verbose_name="Tipo de Cambio",
                    ),
                ),
                (
                    "total_amount_pen",
                    models.DecimalField(
                        decimal_places=2,
                        default=0.0,
                        max_digits=12,
                        verbose_name="Total Contable (Soles)",
                    ),
                ),
                (
                    "tax_rate",
                    models.DecimalField(
                        choices=[
                            (0.18, "18%"),
                            (0.1, "10%"),
                            (0.0, "0% (Exonerado/Inafecto)"),
                        ],
                        decimal_places=2,
                        default=0.18,
                        max_digits=5,
                    ),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=12)),
                ("tax_amount", models.DecimalField(decimal_places=2, max_digits=12)),
                ("total", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "extra_tax_type",
                    models.CharField(
                        choices=[
                            ("NONE", "Ninguno"),
                            ("PERCEPTION", "Percepción"),
                            ("RETENTION", "Retención"),
                            ("DETRACTION", "Detracción"),
                        ],
                        default="NONE",
                        max_length=20,
                    ),
                ),
                (
                    "extra_tax_rate",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=5),
                ),
                (
                    "extra_tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_net_pay",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "payment_condition",
                    models.CharField(
                        choices=[("CASH", "Contado"), ("CREDIT", "Crédito")],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "payment_status",
                    models.CharField(
                        choices=[("PAID", "Pagado"), ("PENDING", "Pendiente")],
                        default="PAID",
                        max_length=20,
                    ),
                ),
                (
                    "transaction_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                (
                    "area",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="purchases",
                        to="purchases.area",
                        verbose_name="Área",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "category",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="purchases.expensecategory",
                    ),
                ),
            ],
        ),
    ]
