# Generated by Django 5.2.10 on 2026-04-20 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("inventory", "0002_initial"),
        ("purchases", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="purchase",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="product",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="purchase",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="purchases.purchase",
            ),
        ),
        migrations.AddField(
            model_name="purchase",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="purchases.supplier"
            ),
        ),
        migrations.AddField(
            model_name="suppliertransaction",
            name="supplier",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="purchases.supplier"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="areamonthlyadjustment",
            unique_together={("area", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="areamonthlylimit",
            unique_together={("area", "year", "month")},
        ),
    ]
