# Generated by Django 5.2.10 on 2026-05-05 10:24

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0002_initial"),
        ("purchases", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "note_type",
                    models.CharField(
                        choices=[("07", "Nota de Crédito"), ("08", "Nota de Débito")],
                        default="07",
                        max_length=2,
                    ),
                ),
                ("series", models.CharField(max_length=20)),
                ("number", models.CharField(max_length=20)),
                ("issue_date", models.DateField(default=django.utils.timezone.now)),
                (
                    "reason",
                    models.CharField(default="Devolución / Descuento", max_length=255),
                ),
                (
                    "affects_inventory",
                    models.BooleanField(
                        default=True,
                        help_text="Marcar si esta nota implica devolver o ingresar productos físicos al almacén.",
                    ),
                ),
                (
                    "currency",
                    models.CharField(
                        choices=[("PEN", "Soles (S/)"), ("USD", "Dólares ($)")],
                        default="PEN",
                        max_length=3,
                    ),
                ),
                (
                    "exchange_rate",
                    models.DecimalField(decimal_places=3, default=1.0, max_digits=6),
                ),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_amount_pen",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "purchase",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="notes",
                        to="purchases.purchase",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PurchaseNoteDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("description", models.CharField(max_length=255)),
                (
                    "quantity",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
                ),
                (
                    "unit_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total_value",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_percentage",
                    models.DecimalField(decimal_places=2, default=18.0, max_digits=5),
                ),
                (
                    "note",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="purchases.purchasenote",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
        ),
    ]
