# Generated by Django 5.2.10 on 2026-05-05 16:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0003_purchasenote_purchasenotedetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedetail",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.area",
            ),
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.expensecategory",
            ),
        ),
        migrations.AddField(
            model_name="purchasenotedetail",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.area",
            ),
        ),
        migrations.AddField(
            model_name="purchasenotedetail",
            name="category",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="purchases.expensecategory",
            ),
        ),
    ]
