# Generated by Django 5.2.10 on 2026-05-05 17:33

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0005_auto_20260225_1707"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="area",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="category",
        ),
    ]
