# Generated by Django 5.2.10 on 2026-05-18 10:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("purchases", "0006_remove_purchase_area_remove_purchase_category"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="purchase",
            constraint=models.UniqueConstraint(
                fields=("supplier", "document_type", "series", "number"),
                name="unique_supplier_purchase_document",
            ),
        ),
    ]
