# Generated by Django 5.2.10 on 2026-05-18 17:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0007_purchase_unique_supplier_purchase_document"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("FACTURA", "Factura"),
                    ("BOLETA", "Boleta"),
                    ("RXH", "Recibo por Honorarios"),
                    ("NOTA_VENTA", "Nota de Venta"),
                    ("NOTA_CREDITO", "Nota de Crédito"),
                    ("NOTA_DEBITO", "Nota de Débito"),
                    ("TICKET", "Ticket"),
                    ("RECIBO_DE_SERVICIOS", "Recibo de Servicios"),
                    ("SIN_ESPECIFICAR", "Sin especificar"),
                    ("MOVILIDAD", "Movilidad"),
                ],
                default="FACTURA",
                max_length=20,
            ),
        ),
    ]
