# Generated by Django 5.2.10 on 2026-05-18 17:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("purchases", "0008_alter_purchase_document_type"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="areamonthlyadjustment",
            unique_together=set(),
        ),
        migrations.AlterUniqueTogether(
            name="areamonthlylimit",
            unique_together=set(),
        ),
        migrations.AddField(
            model_name="areamonthlyadjustment",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
        migrations.AddField(
            model_name="areamonthlylimit",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
        migrations.AlterField(
            model_name="area",
            name="branch",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.CASCADE,
                to="branches.branch",
            ),
        ),
        migrations.CreateModel(
            name="AreaBranchBudget",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "budget_limit",
                    models.DecimalField(decimal_places=2, default=0, max_digits=12),
                ),
                (
                    "area",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="branch_configs",
                        to="purchases.area",
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
            options={
                "unique_together": {("area", "branch")},
            },
        ),
    ]
