# Generated by Django 5.2.10 on 2026-05-18 17:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("purchases", "0010_auto_20260228_1717"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="area",
            name="branch",
        ),
        migrations.RemoveField(
            model_name="area",
            name="budget_limit",
        ),
        migrations.AlterField(
            model_name="area",
            name="name",
            field=models.CharField(max_length=100, unique=True),
        ),
        migrations.AlterField(
            model_name="areamonthlyadjustment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="branches.branch"
            ),
        ),
        migrations.AlterField(
            model_name="areamonthlylimit",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="branches.branch"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="areamonthlyadjustment",
            unique_together={("area", "branch", "year", "month")},
        ),
        migrations.AlterUniqueTogether(
            name="areamonthlylimit",
            unique_together={("area", "branch", "year", "month")},
        ),
    ]
