# Generated by Django 5.2.10 on 2026-05-13 09:30

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0011_remove_area_branch_remove_area_budget_limit_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchase",
            name="tax_rate",
            field=models.DecimalField(
                choices=[
                    (0.18, "18%"),
                    (0.1, "10%"),
                    (0.105, "10.5%"),
                    (0.0, "0% (Exonerado/Inafecto)"),
                ],
                decimal_places=2,
                default=0.18,
                max_digits=5,
            ),
        ),
    ]
