# Generated by Django 5.2.10 on 2026-05-22 16:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0012_alter_purchase_tax_rate"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="purchase",
            name="payment_condition",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="payment_method",
        ),
        migrations.RemoveField(
            model_name="purchase",
            name="transaction_number",
        ),
        migrations.AlterField(
            model_name="purchase",
            name="payment_status",
            field=models.CharField(
                choices=[("PAID", "Pagado"), ("PENDING", "Pendiente")],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="SupplierTransaction",
        ),
    ]
