# Generated by Django 5.2.10 on 2026-05-24 14:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0013_remove_purchase_payment_condition_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasedetail",
            name="invoice_unit",
            field=models.CharField(
                blank=True,
                default="UNIDAD",
                help_text="Unidad de medida según la factura física (Ej: Caja, Fardo)",
                max_length=50,
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="purchasedetail",
            name="units_per_package",
            field=models.DecimalField(
                decimal_places=2,
                default=1.0,
                help_text="Cuántas unidades base vienen en este empaque (Ej: 24)",
                max_digits=10,
            ),
        ),
    ]
