# Generated by Django 5.2.10 on 2026-05-24 14:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0014_purchasedetail_invoice_unit_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="purchasenotedetail",
            name="invoice_unit",
            field=models.CharField(
                blank=True, default="UNIDAD", max_length=50, null=True
            ),
        ),
        migrations.AddField(
            model_name="purchasenotedetail",
            name="units_per_package",
            field=models.DecimalField(decimal_places=2, default=1.0, max_digits=10),
        ),
    ]
