# Generated by Django 5.2.10 on 2026-05-26 17:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0008_alter_product_unit_of_measure"),
        ("purchases", "0015_purchasenotedetail_invoice_unit_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="SupplierProductPrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "unit_price",
                    models.DecimalField(
                        decimal_places=2,
                        help_text="Último precio de compra registrado",
                        max_digits=10,
                    ),
                ),
                (
                    "last_purchase_date",
                    models.DateField(
                        blank=True,
                        help_text="Fecha de la última compra a este precio",
                        null=True,
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="supplier_prices",
                        to="inventory.product",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="product_prices",
                        to="purchases.supplier",
                    ),
                ),
            ],
            options={
                "verbose_name": "Precio por Proveedor",
                "verbose_name_plural": "Precios por Proveedor",
                "unique_together": {("supplier", "product")},
            },
        ),
    ]
