# Generated by Django 5.2.10 on 2026-05-24 17:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("purchases", "0016_supplierproductprice"),
    ]

    operations = [
        migrations.AlterField(
            model_name="purchasedetail",
            name="quantity",
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchasedetail",
            name="unit_value",
            field=models.DecimalField(decimal_places=5, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchasedetail",
            name="units_per_package",
            field=models.DecimalField(
                decimal_places=5,
                default=1.0,
                help_text="Cuántas unidades base vienen en este empaque",
                max_digits=14,
            ),
        ),
        migrations.AlterField(
            model_name="purchasenotedetail",
            name="quantity",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchasenotedetail",
            name="unit_value",
            field=models.DecimalField(decimal_places=5, default=0.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="purchasenotedetail",
            name="units_per_package",
            field=models.DecimalField(decimal_places=5, default=1.0, max_digits=14),
        ),
        migrations.AlterField(
            model_name="supplierproductprice",
            name="unit_price",
            field=models.DecimalField(
                decimal_places=5,
                help_text="Último precio de compra registrado",
                max_digits=14,
            ),
        ),
    ]
