# Generated by Django 5.2.10 on 2026-05-24 14:45

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_branch_web_boleta_series_branch_web_factura_series"),
        ("inventory", "0017_product_colab_price_alter_product_parent"),
        ("purchases", "0017_alter_purchasedetail_quantity_and_more"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PurchaseOrder",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "code",
                    models.CharField(
                        help_text="Ej: OC-00000001", max_length=30, unique=True
                    ),
                ),
                (
                    "delivery_mode",
                    models.CharField(
                        choices=[
                            ("STORE_PICKUP", "Recojo en Tienda"),
                            ("LOCAL_DELIVERY", "Entrega en Local"),
                        ],
                        default="LOCAL_DELIVERY",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        help_text="Ej: EFECTIVO, A CUENTA, TRANSFERENCIA", max_length=50
                    ),
                ),
                (
                    "payment_term",
                    models.CharField(
                        blank=True,
                        help_text="Plazo de pago, Ej: 15 días",
                        max_length=100,
                        null=True,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("OPEN", "Abierta"),
                            ("PARTIAL", "Parcial"),
                            ("CLOSED", "Cerrado"),
                            ("CANCELED", "Anulado"),
                        ],
                        default="OPEN",
                        max_length=15,
                    ),
                ),
                ("issue_date", models.DateTimeField(default=django.utils.timezone.now)),
                (
                    "subtotal",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "tax_amount",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0.0, max_digits=12),
                ),
                ("notes", models.TextField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="branches.branch",
                    ),
                ),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="purchase_orders",
                        to="purchases.supplier",
                    ),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="purchase",
            name="purchase_order",
            field=models.ForeignKey(
                blank=True,
                help_text="Orden de Compra que originó este documento contable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="purchases",
                to="purchases.purchaseorder",
            ),
        ),
        migrations.CreateModel(
            name="PurchaseOrderDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "invoice_unit",
                    models.CharField(
                        default="UNIDAD",
                        help_text="Unidad del proveedor (Ej: Caja, Fardo)",
                        max_length=50,
                    ),
                ),
                (
                    "units_per_package",
                    models.DecimalField(
                        decimal_places=5,
                        default=1.0,
                        help_text="Conversión a stock base",
                        max_digits=14,
                    ),
                ),
                (
                    "quantity_ordered",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=14,
                        verbose_name="Cantidad Solicitada",
                    ),
                ),
                (
                    "quantity_received",
                    models.DecimalField(
                        decimal_places=5,
                        default=0.0,
                        max_digits=14,
                        verbose_name="Cantidad Recibida",
                    ),
                ),
                (
                    "unit_value",
                    models.DecimalField(
                        decimal_places=5,
                        max_digits=14,
                        verbose_name="Valor Unitario (Sin Impuesto)",
                    ),
                ),
                (
                    "total_value",
                    models.DecimalField(
                        decimal_places=2, max_digits=12, verbose_name="Total Línea"
                    ),
                ),
                (
                    "is_bonus",
                    models.BooleanField(
                        default=False, verbose_name="Es Bonificación (Costo Cero)"
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
                (
                    "purchase_order",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="purchases.purchaseorder",
                    ),
                ),
            ],
        ),
    ]
