# Generated by Django 5.2.10 on 2026-05-25 17:46

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0002_branch_web_boleta_series_branch_web_factura_series"),
        ("sales", "0010_sale_json_response"),
    ]

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(help_text="Ej: Día del Niño", max_length=200),
                ),
                ("date", models.DateField(blank=True, null=True)),
                ("has_specific_schedule", models.BooleanField(default=False)),
                ("available_schedules", models.JSONField(blank=True, default=list)),
                ("is_active", models.BooleanField(default=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="events",
                        to="branches.branch",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="EventRegistration",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "ticket_code",
                    models.CharField(
                        help_text="Ej: E-TRU001", max_length=20, unique=True
                    ),
                ),
                (
                    "schedule_selected",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "operation_number",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                ("observations", models.TextField(blank=True, null=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("AVAILABLE", "Disponible"), ("REDEEMED", "Canjeado")],
                        default="AVAILABLE",
                        max_length=20,
                    ),
                ),
                ("redeemed_at", models.DateTimeField(blank=True, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "event",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="registrations",
                        to="events.event",
                    ),
                ),
                (
                    "sale",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="event_ticket",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
