# Generated by Django 5.2.10 on 2026-05-25 09:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="redeemed_quantity",
            field=models.IntegerField(
                default=0, help_text="Cantidad de personas que ya ingresaron"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="total_quantity",
            field=models.IntegerField(
                default=1, help_text="Total de entradas compradas"
            ),
        ),
    ]
