# Generated by Django 5.2.10 on 2026-05-25 11:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0002_eventregistration_redeemed_quantity_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="redeemed_breakdown",
            field=models.JSONField(blank=True, default=dict),
        ),
    ]
