# Generated by Django 5.2.10 on 2026-05-25 12:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0003_eventregistration_redeemed_breakdown"),
    ]

    operations = [
        migrations.AddField(
            model_name="eventregistration",
            name="advisor",
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
