# Generated by Django 5.2.10 on 2026-05-23 12:27

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("events", "0004_eventregistration_advisor"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="form_schema",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Estructura de las preguntas dinámicas",
            ),
        ),
        migrations.AddField(
            model_name="event",
            name="is_advanced_registration",
            field=models.BooleanField(
                default=False, help_text="Activar para carreras o formularios dinámicos"
            ),
        ),
        migrations.AddField(
            model_name="eventregistration",
            name="attendee_data",
            field=models.JSONField(
                blank=True, default=list, help_text="Respuestas al formulario avanzado"
            ),
        ),
    ]
