"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.10.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""

import os
from datetime import timedelta
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

env = environ.Env()

environ.Env.read_env(os.path.join(BASE_DIR, ".env"))


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env.bool("DEBUG", default=False)

APPEND_SLASH = True

# ==============================================================================
# CONFIGURACIÓN DINÁMICA DE HOSTS Y CORS (Basado en DEBUG)
# ==============================================================================

if DEBUG:
    # MODO DESARROLLO (Local)
    ALLOWED_HOSTS = [
        "localhost",
        "127.0.0.1",
        "testserver",
        "192.168.18.141",
        "10.253.21.215",
    ]

    CORS_ALLOWED_ORIGINS = [
        "http://localhost:5173",  # React/Vite
        "http://localhost:3000",
        "http://127.0.0.1:5173",
        "http://localhost",
        "capacitor://localhost",
    ]
else:
    # MODO PRODUCCIÓN (Servidor en la Nube)
    ALLOWED_HOSTS = env.list(
        "ALLOWED_HOSTS",
        default=[
            "api.ludicuspark.com",
            "app-erp.ludicuspark.com",
            "www.app-erp.ludicuspark.com",
        ],
    )

    CORS_ALLOWED_ORIGINS = env.list(
        "CORS_ALLOWED_ORIGINS",
        default=[
            "https://app-erp.ludicuspark.com",
            "https://www.app-erp.ludicuspark.com",
            # ORÍGENES PARA EL APK DE CAPACITOR
            "http://localhost",
            "capacitor://localhost",
            "http://localhost:5173",
        ],
    )

# ==============================================================================


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    "rest_framework",
    "django_filters",
    "rest_framework_simplejwt",
    "corsheaders",
    "users",
    "company",
    "branches",
    "cash",
    "inventory",
    "sales",
    "purchases",
    "reports",
    "branches",
    "core",
    "cash",
    "treasury",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.security.SecurityMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
]

ROOT_URLCONF = "core.urls"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "core.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.2/ref/settings/#databases

# Se modifica para MySQL con Connection Pool
DATABASES = {
    "default": {
        "ENGINE": "dj_db_conn_pool.backends.mysql",
        "NAME": env("DB_NAME"),
        "USER": env("DB_USER"),
        "PASSWORD": env("DB_PASSWORD"),
        "HOST": env("DB_HOST"),
        "PORT": env("DB_PORT"),
        "OPTIONS": {
            "init_command": "SET sql_mode='STRICT_TRANS_TABLES'",
        },
        "POOL_OPTIONS": {
            "POOL_SIZE": 10,
            "MAX_OVERFLOW": 10,
            "RECYCLE": 30,  # Banahosting mata conexiones rápido, las reciclamos cada 30 seg
            "PRE_PING": True,  # Verifica si la conexión está viva antes de usarla
        },
    }
}

APISPERU_URL = env("APISPERU_URL", default="")
APISPERU_TOKEN = env("APISPERU_TOKEN", default="")
APISPERU_CONSULTA_TOKEN = env("APISPERU_CONSULTA_TOKEN", default="")
FACTILIZA_TOKEN = env("FACTILIZA_TOKEN", default="")

# DRF CONFIG
REST_FRAMEWORK = {
    "DEFAULT_AUTHENTICATION_CLASSES": (
        "rest_framework_simplejwt.authentication.JWTAuthentication",
        "core.pagination.StandardResultsSetPagination",
    )
}

# CORS PARA PRODUCCION
# CORS_ALLOWED_ORIGINS = [
#     "https://app-erp.ludicuspark.com",  # 👈 Agregado https://
#     "https://www.app-erp.ludicuspark.com",  # 👈 Agregado https://
#     "http://localhost:5173",  # Localhost suele ser http
# ]


CORS_ALLOWED_ORIGINS = [
    "http://localhost:5173",  # Puerto por defecto de Vite
    "http://localhost:3000",
]


# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        "NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.MinimumLengthValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.CommonPasswordValidator",
    },
    {
        "NAME": "django.contrib.auth.password_validation.NumericPasswordValidator",
    },
]

SIMPLE_JWT = {
    "ACCESS_TOKEN_LIFETIME": timedelta(days=1),  # <--- SEGURO
    "REFRESH_TOKEN_LIFETIME": timedelta(days=7),  # <--- La sesión dura 7 días
    "ROTATE_REFRESH_TOKENS": True,  # <--- IMPORTANTE: Cambia el refresh token cada vez que se usa
    "BLACKLIST_AFTER_ROTATION": False,  # <--- Invalida los viejos (Seguridad extra)
}


# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = "es-pe"

TIME_ZONE = "America/Lima"

USE_I18N = True

USE_TZ = False


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

STATIC_URL = "static/"

# PRODUCCION
# STATIC_ROOT = os.path.join(BASE_DIR, "staticfiles")
# STATICFILES_STORAGE = "whitenoise.storage.CompressedManifestStaticFilesStorage"


# Media files (Archivos físicos generados por el sistema: XML, ZIP, PDFs)
MEDIA_URL = "/media/"
MEDIA_ROOT = os.path.join(BASE_DIR, "media")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"
