# Generated by Django 5.2.10 on 2026-04-20 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Category",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
                ("description", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
            options={
                "verbose_name_plural": "Categories",
            },
        ),
        migrations.CreateModel(
            name="Product",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=200)),
                (
                    "product_type",
                    models.CharField(
                        choices=[
                            ("STOCKED", "Producto Almacenable (Venta)"),
                            ("CONSUMABLE", "Consumible (Uso Interno)"),
                            ("SERVICE", "Servicio"),
                            ("ASSET", "Activo Fijo"),
                        ],
                        default="STOCKED",
                        max_length=20,
                    ),
                ),
                ("sku", models.CharField(blank=True, max_length=50, unique=True)),
                ("is_sellable", models.BooleanField(default=True)),
                ("is_purchasable", models.BooleanField(default=True)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Stock",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.IntegerField(default=0)),
                (
                    "average_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="Transfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de Recepción"),
                            ("COMPLETED", "Completado / Recibido"),
                            ("CANCELLED", "Cancelado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                ("observation", models.TextField(blank=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name="TransferDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.PositiveIntegerField()),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Kardex",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("IN_PURCHASE", "Entrada por Compra"),
                            ("IN_TRANSFER", "Entrada por Traslado"),
                            ("IN_ADJUSTMENT", "Entrada por Ajuste (+ Sobrante)"),
                            ("OUT_SALE", "Salida por Venta"),
                            ("OUT_TRANSFER", "Salida por Traslado"),
                            ("OUT_INTERNAL", "Salida por Consumo Interno"),
                            ("OUT_DAMAGE", "Salida por Merma/Daño"),
                            ("OUT_ADJUSTMENT", "Salida por Ajuste (- Faltante)"),
                        ],
                        max_length=20,
                    ),
                ),
                ("quantity", models.IntegerField()),
                ("unit_cost", models.DecimalField(decimal_places=4, max_digits=12)),
                ("total_cost", models.DecimalField(decimal_places=2, max_digits=12)),
                ("balance_quantity", models.IntegerField()),
                (
                    "balance_unit_cost",
                    models.DecimalField(decimal_places=4, max_digits=12),
                ),
                (
                    "balance_total_cost",
                    models.DecimalField(decimal_places=2, max_digits=14),
                ),
                ("description", models.CharField(blank=True, max_length=255)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="branches.branch",
                    ),
                ),
            ],
        ),
    ]
