# Generated by Django 5.2.10 on 2026-05-13 17:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
        ("inventory", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="InventoryAdjustment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "type",
                    models.CharField(
                        choices=[
                            ("MERMA_OUT", "Salida por Merma / Daño"),
                            ("MERMA_RETURN", "Devolución por Merma (Reingreso)"),
                            ("INTERNAL", "Consumo Interno"),
                            ("ADJUST_IN", "Ajuste de Entrada (Sobrante)"),
                            ("ADJUST_OUT", "Ajuste de Salida (Faltante)"),
                            ("INITIAL", "Inventario Inicial"),
                        ],
                        max_length=20,
                    ),
                ),
                ("reason", models.CharField(max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="InventoryAdjustmentDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
                ),
            ],
        ),
        migrations.CreateModel(
            name="ProductRecipe",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=4, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50, unique=True)),
                ("color", models.CharField(default="#3B82F6", max_length=20)),
            ],
        ),
        migrations.AlterModelOptions(
            name="category",
            options={},
        ),
        migrations.AddField(
            model_name="category",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="kardex",
            name="reference_document",
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name="product",
            name="has_recipe",
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name="product",
            name="is_active",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="manage_stock",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("NIU", "Unidades (NIU)"),
                    ("KGM", "Kilogramos (KGM)"),
                    ("LTR", "Litros (LTR)"),
                    ("MTR", "Metros (MTR)"),
                    ("ZZ", "Servicio (ZZ)"),
                ],
                default="NIU",
                max_length=5,
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="Habilita/Deshabilita el producto solo para esta sede",
            ),
        ),
        migrations.AddField(
            model_name="stock",
            name="min_stock",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="balance_quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=12),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN_PURCHASE", "Entrada por Compra"),
                    ("IN_ADJUSTMENT", "Ajuste de Entrada"),
                    ("IN_TRANSFER", "Transferencia de Entrada"),
                    ("IN_RETURN", "Devolución por Merma"),
                    ("IN_PRODUCTION", "Entrada por Producción"),
                    ("OUT_SALE", "Salida por Venta"),
                    ("OUT_MERMA", "Salida por Merma"),
                    ("OUT_ADJUSTMENT", "Ajuste de Salida"),
                    ("OUT_TRANSFER", "Transferencia de Salida"),
                    ("OUT_RECIPE", "Salida por Consumo de Receta"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="category",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="inventory.category",
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="price",
            field=models.DecimalField(decimal_places=2, default=0.0, max_digits=10),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("STOCKED", "Producto Almacenable"),
                    ("CONSUMABLE", "Materia Prima / Insumo"),
                    ("FINISHED", "Producto Terminado (Receta)"),
                    ("SERVICE", "Servicio"),
                ],
                default="STOCKED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="stock",
            name="quantity",
            field=models.DecimalField(decimal_places=4, default=0.0, max_digits=12),
        ),
        migrations.AlterField(
            model_name="transfer",
            name="status",
            field=models.CharField(
                choices=[
                    ("PENDING", "Pendiente"),
                    ("COMPLETED", "Completado"),
                    ("CANCELLED", "Cancelado"),
                ],
                default="PENDING",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="transferdetail",
            name="quantity",
            field=models.DecimalField(decimal_places=4, max_digits=10),
        ),
        migrations.AddConstraint(
            model_name="stock",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gte", 0)), name="prevent_negative_stock"
            ),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="inventoryadjustment",
            name="created_by",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="inventoryadjustmentdetail",
            name="adjustment",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="details",
                to="inventory.inventoryadjustment",
            ),
        ),
        migrations.AddField(
            model_name="inventoryadjustmentdetail",
            name="product",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="inventory.product"
            ),
        ),
        migrations.AddField(
            model_name="productrecipe",
            name="finished_product",
            field=models.ForeignKey(
                limit_choices_to={"has_recipe": True},
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="productrecipe",
            name="ingredient",
            field=models.ForeignKey(
                limit_choices_to={"manage_stock": True},
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_recipes",
                to="inventory.product",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="tags",
            field=models.ManyToManyField(
                blank=True, related_name="products", to="inventory.tag"
            ),
        ),
        migrations.AlterUniqueTogether(
            name="productrecipe",
            unique_together={("finished_product", "ingredient")},
        ),
    ]
