# Generated by Django 5.2.10 on 2026-05-17 16:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0004_area_product_area"),
        ("purchases", "0008_alter_purchase_document_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="area",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="products",
                to="purchases.area",
            ),
        ),
    ]
