# Generated by Django 5.2.10 on 2026-05-17 16:14

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0005_alter_product_area"),
    ]

    operations = [
        migrations.AlterField(
            model_name="kardex",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN_PURCHASE", "Entrada por Compra"),
                    ("IN_ADJUSTMENT", "Ajuste de Entrada"),
                    ("IN_TRANSFER", "Transferencia de Entrada"),
                    ("IN_RETURN", "Devolución por Merma"),
                    ("IN_PRODUCTION", "Entrada por Producción"),
                    ("OUT_SALE", "Salida por Venta"),
                    ("OUT_MERMA", "Salida por Merma"),
                    ("OUT_ADJUSTMENT", "Ajuste de Salida"),
                    ("OUT_TRANSFER", "Transferencia de Salida"),
                    ("OUT_RECIPE", "Salida por Consumo de Receta"),
                    ("OUT_RETURN", "Salida por Devolución a Proveedor"),
                ],
                max_length=20,
            ),
        ),
    ]
