# Generated by Django 5.2.10 on 2026-05-24 16:07

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0006_alter_kardex_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="inventoryadjustment",
            name="type",
            field=models.CharField(
                choices=[
                    ("MERMA_OUT", "Salida por Merma / Daño"),
                    ("MERMA_RETURN", "Devolución por Merma (Reingreso)"),
                    ("INTERNAL", "Consumo Interno"),
                    ("ADJUST_IN", "Ajuste de Entrada (Sobrante)"),
                    ("ADJUST_OUT", "Ajuste de Salida (Faltante)"),
                    ("INITIAL", "Inventario Inicial"),
                    ("PRODUCTION", "Orden de Producción"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="kardex",
            name="type",
            field=models.CharField(
                choices=[
                    ("IN_PURCHASE", "Entrada por Compra"),
                    ("IN_ADJUSTMENT", "Ajuste de Entrada"),
                    ("IN_TRANSFER", "Transferencia de Entrada"),
                    ("IN_RETURN", "Devolución por Merma"),
                    ("IN_PRODUCTION", "Entrada por Producción (Subreceta)"),
                    ("OUT_SALE", "Salida por Venta"),
                    ("OUT_MERMA", "Salida por Merma"),
                    ("OUT_ADJUSTMENT", "Ajuste de Salida"),
                    ("OUT_TRANSFER", "Transferencia de Salida"),
                    ("OUT_RECIPE", "Salida por Consumo de Receta"),
                    ("OUT_PRODUCTION", "Salida a Producción"),
                    ("OUT_RETURN", "Salida por Devolución a Proveedor"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="product_type",
            field=models.CharField(
                choices=[
                    ("STOCKED", "Producto Almacenable"),
                    ("CONSUMABLE", "Materia Prima / Insumo"),
                    ("INTERMEDIATE", "Producto Intermedio / Subreceta"),
                    ("FINISHED", "Producto Terminado (Receta)"),
                    ("SERVICE", "Servicio"),
                ],
                default="STOCKED",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="productrecipe",
            name="finished_product",
            field=models.ForeignKey(
                limit_choices_to={
                    "product_type__in": ["FINISHED", "INTERMEDIATE", "STOCKED"]
                },
                on_delete=django.db.models.deletion.CASCADE,
                related_name="recipe_ingredients",
                to="inventory.product",
            ),
        ),
    ]
