# Generated by Django 5.2.10 on 2026-05-24 17:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0007_alter_inventoryadjustment_type_alter_kardex_type_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("NIU", "Unidades (NIU)"),
                    ("KGM", "Kilogramos (KGM)"),
                    ("LTR", "Litros (LTR)"),
                    ("MTR", "Metros (MTR)"),
                    ("GLN", "Galones (GLN)"),
                    ("BLS", "Bolsas (BLS)"),
                    ("ZZ", "Servicio (ZZ)"),
                ],
                default="NIU",
                max_length=5,
            ),
        ),
    ]
