# Generated by Django 5.2.10 on 2026-05-26 09:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0010_alter_product_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="stock",
            name="selling_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio de venta para esta sede (si es null, usa el precio global del producto)",
                max_digits=10,
                null=True,
            ),
        ),
    ]
