# Generated by Django 5.2.10 on 2026-05-26 13:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0011_stock_selling_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="productrecipe",
            name="ingredient",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="used_in_recipes",
                to="inventory.product",
            ),
        ),
    ]
