# Generated by Django 5.2.10 on 2026-05-26 16:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0002_branch_web_boleta_series_branch_web_factura_series"),
        ("inventory", "0012_alter_productrecipe_ingredient"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PhysicalInventory",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("reference", models.CharField(blank=True, max_length=50)),
                (
                    "status",
                    models.CharField(
                        choices=[
                            ("DRAFT", "En Proceso (Borrador)"),
                            ("CLOSED", "Cerrado / Auditado"),
                        ],
                        default="DRAFT",
                        max_length=20,
                    ),
                ),
                (
                    "notes",
                    models.TextField(
                        blank=True, help_text="Observaciones generales del conteo"
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("closed_at", models.DateTimeField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="physical_inventories",
                        to="branches.branch",
                    ),
                ),
                (
                    "created_by",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="created_inventories",
                        to=settings.AUTH_USER_MODEL,
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="PhysicalInventoryDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "system_stock",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Lo que decía el sistema",
                        max_digits=12,
                    ),
                ),
                (
                    "unit_cost",
                    models.DecimalField(
                        decimal_places=4,
                        help_text="Costo promedio en ese momento",
                        max_digits=12,
                    ),
                ),
                (
                    "physical_stock",
                    models.DecimalField(
                        decimal_places=4,
                        default=0,
                        help_text="Lo que realmente hay",
                        max_digits=12,
                    ),
                ),
                (
                    "difference",
                    models.DecimalField(decimal_places=4, default=0, max_digits=12),
                ),
                (
                    "action_taken",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente de decisión"),
                            ("ADJUST", "Ajustar Sistema (Asumir merma/sobrante)"),
                            ("IGNORE", "Ignorar (Repondrán físico)"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "action_notes",
                    models.CharField(
                        blank=True,
                        help_text="Ej: Se lo cobramos a Juan",
                        max_length=255,
                    ),
                ),
                (
                    "inventory",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="details",
                        to="inventory.physicalinventory",
                    ),
                ),
                (
                    "product",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="inventory.product",
                    ),
                ),
            ],
            options={
                "unique_together": {("inventory", "product")},
            },
        ),
    ]
