# Generated by Django 5.2.10 on 2026-05-26 16:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0013_physicalinventory_physicalinventorydetail"),
    ]

    operations = [
        migrations.AddField(
            model_name="physicalinventory",
            name="end_date",
            field=models.DateField(
                help_text="Fecha de fin del periodo auditado", null=True
            ),
        ),
        migrations.AddField(
            model_name="physicalinventory",
            name="start_date",
            field=models.DateField(
                help_text="Fecha de inicio del periodo auditado", null=True
            ),
        ),
        migrations.AddField(
            model_name="physicalinventorydetail",
            name="initial_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Stock al inicio del periodo",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="physicalinventorydetail",
            name="total_inputs",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Entradas/Compras en el periodo",
                max_digits=12,
            ),
        ),
        migrations.AddField(
            model_name="physicalinventorydetail",
            name="total_outputs",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Salidas/Consumos en el periodo",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="physicalinventorydetail",
            name="action_notes",
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name="physicalinventorydetail",
            name="physical_stock",
            field=models.DecimalField(
                decimal_places=4,
                default=0,
                help_text="Conteo físico real",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="physicalinventorydetail",
            name="system_stock",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Stock Teórico Final (Inicial + Entradas - Salidas)",
                max_digits=12,
            ),
        ),
        migrations.AlterField(
            model_name="physicalinventorydetail",
            name="unit_cost",
            field=models.DecimalField(
                decimal_places=4,
                help_text="Costo promedio al cierre del periodo",
                max_digits=12,
            ),
        ),
    ]
