# Generated by Django 5.2.10 on 2026-05-24 12:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_physicalinventory_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="product",
            name="unit_of_measure",
            field=models.CharField(
                choices=[
                    ("NIU", "Unidad"),
                    ("CAJ", "Caja"),
                    ("FARD", "Fardo"),
                    ("PAA", "Paquete"),
                    ("SAC", "Saco"),
                    ("LTR", "Litro"),
                    ("KGM", "Kilogramo"),
                    ("MIL", "Millar"),
                    ("GLN", "Galón"),
                    ("BLS", "Bolsa"),
                    ("LATA", "Lata"),
                    ("BT", "Botella"),
                    ("ZZ", "Servicio"),
                    ("RLL", "Rollo"),
                ],
                default="NIU",
                max_length=20,
            ),
        ),
    ]
