# Generated by Django 5.2.10 on 2026-05-24 13:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0015_alter_product_unit_of_measure"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="is_group",
            field=models.BooleanField(
                default=False,
                help_text="¿Es un botón agrupador visual? (Ej: El botón 'GASEOSAS')",
            ),
        ),
        migrations.AddField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Si este producto es una variante (Ej: Inca Kola), selecciona el grupo padre aquí.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="inventory.product",
            ),
        ),
    ]
