# Generated by Django 5.2.10 on 2026-05-24 16:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0016_product_is_group_product_parent"),
    ]

    operations = [
        migrations.AddField(
            model_name="product",
            name="colab_price",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                help_text="Precio especial(Opcional)",
                max_digits=10,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="product",
            name="parent",
            field=models.ForeignKey(
                blank=True,
                help_text="Si este producto es una variante, selecciona el grupo padre aquí.",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="variants",
                to="inventory.product",
            ),
        ),
    ]
