# Generated by Django 5.2.10 on 2026-05-22 16:25

import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("purchases", "0013_remove_purchase_payment_condition_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="PaymentTransaction",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "transaction_type",
                    models.CharField(
                        choices=[
                            ("PAYMENT", "Pago de Factura"),
                            ("ADVANCE", "Anticipo / Saldo a Favor"),
                        ],
                        default="PAYMENT",
                        max_length=20,
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("TRANSFER", "Transferencia"),
                            ("CHECK", "Cheque"),
                            ("BALANCE", "Cruce con Saldo a Favor"),
                        ],
                        default="TRANSFER",
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=12)),
                (
                    "transaction_number",
                    models.CharField(blank=True, max_length=50, null=True),
                ),
                ("payment_date", models.DateField(default=django.utils.timezone.now)),
                ("description", models.CharField(blank=True, max_length=255)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                (
                    "supplier",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="payments",
                        to="purchases.supplier",
                    ),
                ),
            ],
        ),
    ]
