# Generated by Django 5.2.10 on 2026-04-20 02:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="Customer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "name",
                    models.CharField(
                        max_length=200, verbose_name="Nombre / Razón Social"
                    ),
                ),
                (
                    "document_type",
                    models.CharField(
                        choices=[("DNI", "DNI"), ("RUC", "RUC")],
                        default="DNI",
                        max_length=10,
                    ),
                ),
                (
                    "tax_id",
                    models.CharField(
                        max_length=20, unique=True, verbose_name="Documento (DNI/RUC)"
                    ),
                ),
                ("email", models.EmailField(blank=True, max_length=254, null=True)),
                ("phone", models.CharField(blank=True, max_length=20, null=True)),
                ("address", models.CharField(blank=True, max_length=255, null=True)),
                ("created_at", models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name="SaleDetail",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("quantity", models.DecimalField(decimal_places=2, max_digits=10)),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
                (
                    "unit_cost",
                    models.DecimalField(decimal_places=4, default=0, max_digits=10),
                ),
                ("subtotal", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name="SalePayment",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("CARD", "Visa / Yape"),
                            ("TRANSFER", "Transferencia"),
                            ("MIXED", "Pago Mixto"),
                        ],
                        max_length=20,
                    ),
                ),
                ("amount", models.DecimalField(decimal_places=2, max_digits=10)),
                ("reference", models.CharField(blank=True, max_length=50, null=True)),
            ],
        ),
        migrations.CreateModel(
            name="Sale",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("series", models.CharField(default="B001", max_length=4)),
                ("number", models.CharField(default="00000000", max_length=8)),
                (
                    "total",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "payment_method",
                    models.CharField(
                        choices=[
                            ("CASH", "Efectivo"),
                            ("CARD", "Visa / Yape"),
                            ("TRANSFER", "Transferencia"),
                            ("MIXED", "Pago Mixto"),
                        ],
                        default="CASH",
                        max_length=20,
                    ),
                ),
                (
                    "status",
                    models.CharField(
                        choices=[("COMPLETED", "Completada"), ("CANCELED", "Anulada")],
                        default="COMPLETED",
                        max_length=20,
                    ),
                ),
                (
                    "total_gravada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_igv",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_exonerada",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                (
                    "total_inafecta",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("invoice_type_code", models.CharField(default="03", max_length=2)),
                (
                    "sunat_status",
                    models.CharField(
                        choices=[
                            ("PENDING", "Pendiente"),
                            ("SENT", "Enviado"),
                            ("ACCEPTED", "Aceptado"),
                            ("REJECTED", "Rechazado"),
                        ],
                        default="PENDING",
                        max_length=20,
                    ),
                ),
                (
                    "sunat_response_code",
                    models.CharField(blank=True, max_length=10, null=True),
                ),
                ("sunat_description", models.TextField(blank=True, null=True)),
                ("sunat_hash", models.CharField(blank=True, max_length=255, null=True)),
                ("sunat_xml_url", models.TextField(blank=True, null=True)),
                ("sunat_cdr_url", models.TextField(blank=True, null=True)),
                ("sunat_pdf_url", models.TextField(blank=True, null=True)),
                ("json_sent", models.JSONField(blank=True, null=True)),
                (
                    "branch",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="branches.branch",
                    ),
                ),
                (
                    "customer",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        to="sales.customer",
                    ),
                ),
            ],
        ),
    ]
