# Generated by Django 5.2.10 on 2026-04-22 19:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0002_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="CreditNote",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("series", models.CharField(max_length=4)),
                ("number", models.CharField(max_length=8)),
                (
                    "note_type",
                    models.CharField(
                        choices=[("07", "NOTA DE CRÉDITO"), ("08", "NOTA DE DÉBITO")],
                        default="07",
                        max_length=2,
                    ),
                ),
                (
                    "reason_code",
                    models.CharField(
                        choices=[
                            ("01", "ANULACION DE LA OPERACION"),
                            ("07", "DEVOLUCION POR ITEM"),
                            ("13", "CORRECCION POR ERROR EN LA DESCRIPCION"),
                        ],
                        default="01",
                        max_length=2,
                    ),
                ),
                (
                    "description",
                    models.CharField(
                        default="ANULACION DE LA OPERACION", max_length=255
                    ),
                ),
                ("date", models.DateTimeField(auto_now_add=True)),
                ("json_sent", models.JSONField(blank=True, null=True)),
                ("json_response", models.JSONField(blank=True, null=True)),
                ("sunat_pdf_url", models.URLField(blank=True, null=True)),
                (
                    "sale",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="credit_notes",
                        to="sales.sale",
                    ),
                ),
            ],
        ),
    ]
