# Generated by Django 5.2.10 on 2026-05-11 11:21

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0003_creditnote"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorized_courtesies",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="is_courtesy",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Visa / Yape"),
                    ("TRANSFER", "Transferencia"),
                    ("MIXED", "Pago Mixto"),
                    ("COURTESY", "Cortesía (Costo Cero)"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="sale",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales_made",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="salepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Visa / Yape"),
                    ("TRANSFER", "Transferencia"),
                    ("MIXED", "Pago Mixto"),
                    ("COURTESY", "Cortesía (Costo Cero)"),
                ],
                max_length=20,
            ),
        ),
    ]
