# Generated by Django 5.2.10 on 2026-05-11 16:56

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0004_sale_authorized_by_sale_is_courtesy_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="notes",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
