# Generated by Django 5.2.10 on 2026-05-27 12:12

import uuid

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0005_sale_notes"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="is_synced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="sale",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
