# Generated by Django 5.2.10 on 2026-05-27 17:51

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0005_cashregister_boleta_series_and_more"),
        ("sales", "0006_sale_is_synced_sale_uuid"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="shift",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="sales",
                to="cash.cashshift",
            ),
        ),
    ]
