# Generated by Django 5.2.10 on 2026-05-27 13:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0007_sale_shift"),
    ]

    operations = [
        migrations.AlterField(
            model_name="customer",
            name="document_type",
            field=models.CharField(
                choices=[
                    ("DNI", "DNI"),
                    ("RUC", "RUC"),
                    ("CE", "Carné de Extranjería"),
                    ("PASAPORTE", "Pasaporte"),
                ],
                default="DNI",
                max_length=10,
            ),
        ),
    ]
