# Generated by Django 5.2.10 on 2026-05-27 18:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0008_alter_customer_document_type"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="discount_amount",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Monto total descontado",
                max_digits=10,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_authorized_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Supervisor que autorizó el descuento con su PIN",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorized_discounts",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="sale",
            name="discount_reason",
            field=models.CharField(
                blank=True,
                help_text="Razón del descuento (opcional)",
                max_length=255,
                null=True,
            ),
        ),
    ]
