# Generated by Django 5.2.10 on 2026-05-27 18:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0009_sale_discount_amount_sale_discount_authorized_by_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="sale",
            name="json_response",
            field=models.JSONField(blank=True, null=True),
        ),
    ]
