# Generated by Django 5.2.10 on 2026-05-27 11:05

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0010_sale_json_response"),
    ]

    operations = [
        migrations.AlterField(
            model_name="sale",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Visa / Yape"),
                    ("TRANSFER", "Transferencia"),
                    ("PAGO_LINK", "Pago Link"),
                    ("MIXED", "Pago Mixto"),
                    ("COURTESY", "Cortesía (Costo Cero)"),
                ],
                default="CASH",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="salepayment",
            name="payment_method",
            field=models.CharField(
                choices=[
                    ("CASH", "Efectivo"),
                    ("CARD", "Visa / Yape"),
                    ("TRANSFER", "Transferencia"),
                    ("PAGO_LINK", "Pago Link"),
                    ("MIXED", "Pago Mixto"),
                    ("COURTESY", "Cortesía (Costo Cero)"),
                ],
                max_length=20,
            ),
        ),
    ]
