# Generated by Django 5.2.10 on 2026-05-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0011_alter_sale_payment_method_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="creditnote",
            name="sunat_cdr_url",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="sunat_description",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="sunat_hash",
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="sunat_status",
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
        migrations.AddField(
            model_name="creditnote",
            name="sunat_xml_url",
            field=models.URLField(blank=True, null=True),
        ),
    ]
