# Generated by Django 5.2.10 on 2026-05-27 17:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0012_creditnote_sunat_cdr_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_cdr_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_hash",
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_pdf_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_xml_url",
            field=models.URLField(blank=True, max_length=1000, null=True),
        ),
    ]
