# Generated by Django 5.2.10 on 2026-05-27 17:32

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("sales", "0013_alter_creditnote_sunat_cdr_url_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_cdr_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_hash",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_pdf_url",
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="creditnote",
            name="sunat_xml_url",
            field=models.TextField(blank=True, null=True),
        ),
    ]
