# Generated by Django 5.2.10 on 2026-05-26 11:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="branch",
            name="web_boleta_series",
            field=models.CharField(
                default="B099",
                help_text="Serie para boletas hechas desde la web",
                max_length=4,
            ),
        ),
        migrations.AddField(
            model_name="branch",
            name="web_factura_series",
            field=models.CharField(
                default="F099",
                help_text="Serie para facturas hechas desde la web",
                max_length=4,
            ),
        ),
    ]
