# Generated by Django 5.2.10 on 2026-04-20 02:13

import django.contrib.auth.models
import django.contrib.auth.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
        ("branches", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="password")),
                (
                    "last_login",
                    models.DateTimeField(
                        blank=True, null=True, verbose_name="last login"
                    ),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="Designates that this user has all permissions without explicitly assigning them.",
                        verbose_name="superuser status",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={
                            "unique": "A user with that username already exists."
                        },
                        help_text="Required. 150 characters or fewer. Letters, digits and @/./+/-/_ only.",
                        max_length=150,
                        unique=True,
                        validators=[
                            django.contrib.auth.validators.UnicodeUsernameValidator()
                        ],
                        verbose_name="username",
                    ),
                ),
                (
                    "first_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="first name"
                    ),
                ),
                (
                    "last_name",
                    models.CharField(
                        blank=True, max_length=150, verbose_name="last name"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="Designates whether the user can log into this admin site.",
                        verbose_name="staff status",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="Designates whether this user should be treated as active. Unselect this instead of deleting accounts.",
                        verbose_name="active",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.now, verbose_name="date joined"
                    ),
                ),
                ("email", models.EmailField(max_length=254, unique=True)),
                (
                    "role",
                    models.CharField(
                        choices=[
                            ("ADMIN", "Administrador"),
                            ("MANAGER", "Gerente"),
                            ("EMPLOYEE", "Empleado"),
                        ],
                        default="EMPLOYEE",
                        max_length=20,
                    ),
                ),
                (
                    "can_view_users",
                    models.BooleanField(
                        default=False, verbose_name="Usuarios: Gestión"
                    ),
                ),
                (
                    "can_view_pos",
                    models.BooleanField(
                        default=False, verbose_name="Ventas: Punto de Venta"
                    ),
                ),
                (
                    "can_view_sales_list",
                    models.BooleanField(
                        default=False, verbose_name="Ventas: Historial"
                    ),
                ),
                (
                    "can_view_cash",
                    models.BooleanField(default=False, verbose_name="Ver Caja"),
                ),
                (
                    "can_view_products_list",
                    models.BooleanField(
                        default=False, verbose_name="Inventario: Lista"
                    ),
                ),
                (
                    "can_view_products_create",
                    models.BooleanField(
                        default=False, verbose_name="Inventario: Nuevo Producto"
                    ),
                ),
                (
                    "can_view_purchases_create",
                    models.BooleanField(default=False, verbose_name="Compras: Nueva"),
                ),
                (
                    "can_view_purchases_list",
                    models.BooleanField(
                        default=False, verbose_name="Compras: Historial"
                    ),
                ),
                (
                    "can_view_purchases_payable",
                    models.BooleanField(
                        default=False, verbose_name="Compras: Por Pagar"
                    ),
                ),
                (
                    "can_view_purchases_balances",
                    models.BooleanField(default=False, verbose_name="Compras: Saldos"),
                ),
                (
                    "can_view_purchases_suppliers",
                    models.BooleanField(
                        default=False, verbose_name="Compras: Proveedores"
                    ),
                ),
                (
                    "can_view_purchases_budgets",
                    models.BooleanField(
                        default=False, verbose_name="Compras: Presupuestos"
                    ),
                ),
                (
                    "branch",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="users",
                        to="branches.branch",
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={
                "verbose_name": "user",
                "verbose_name_plural": "users",
                "abstract": False,
            },
            managers=[
                ("objects", django.contrib.auth.models.UserManager()),
            ],
        ),
    ]
