# Generated by Django 5.2.10 on 2026-04-23 22:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="can_authorize_voids",
            field=models.BooleanField(
                default=False, verbose_name="Ventas: Autorizar Anulaciones"
            ),
        ),
        migrations.AddField(
            model_name="user",
            name="pin",
            field=models.CharField(
                blank=True,
                help_text="PIN de 4 a 6 dígitos para ingreso y autorizaciones en el POS",
                max_length=6,
                null=True,
                unique=True,
            ),
        ),
    ]
