# Generated by Django 5.2.10 on 2026-02-18 02:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='CashMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('movement_type', models.CharField(choices=[('IN', 'Ingreso'), ('OUT', 'Egreso')], max_length=5)),
                ('concept', models.CharField(choices=[('SALE', 'Venta'), ('EXPENSE', 'Gasto/Compra'), ('DEPOSIT', 'Ingreso Manual'), ('WITHDRAWAL', 'Retiro/Sangría')], max_length=20)),
                ('description', models.CharField(blank=True, max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashRegister',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('is_active', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='CashShift',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('opened_at', models.DateTimeField(auto_now_add=True)),
                ('closed_at', models.DateTimeField(blank=True, null=True)),
                ('initial_balance', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Saldo Inicial')),
                ('final_balance_system', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo Calculado por Sistema')),
                ('final_balance_real', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Saldo Real (Arqueo)')),
                ('difference', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Diferencia (Sobrante/Faltante)')),
                ('status', models.CharField(choices=[('OPEN', 'Abierta'), ('CLOSED', 'Cerrada')], default='OPEN', max_length=10)),
            ],
        ),
    ]
