# Generated by Django 5.2.10 on 2026-04-22 02:13

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("branches", "0001_initial"),
        ("cash", "0002_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="branch",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE, to="branches.branch"
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="cash_register",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="cash.cashregister"
            ),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to=settings.AUTH_USER_MODEL
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="shift",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="movements",
                to="cash.cashshift",
            ),
        ),
    ]
