# Generated by Django 5.2.10 on 2026-05-26 12:45

import uuid

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0003_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name="cashmovement",
            name="authorized_by",
            field=models.ForeignKey(
                blank=True,
                help_text="Usuario supervisor que autorizó el movimiento manual mediante PIN",
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="authorized_cash_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="is_synced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cashmovement",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="is_synced",
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name="cashshift",
            name="uuid",
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
        migrations.AlterField(
            model_name="cashmovement",
            name="concept",
            field=models.CharField(
                choices=[
                    ("SALE", "Venta Efectivo"),
                    ("EXPENSE", "Gasto/Compra"),
                    ("DEPOSIT", "Ingreso Manual"),
                    ("WITHDRAWAL", "Retiro/Sangría"),
                    ("REFUND", "Devolución"),
                ],
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="cashmovement",
            name="user",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="cash_movements",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
