# Generated by Django 5.2.10 on 2026-05-26 13:04

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0004_cashmovement_authorized_by_cashmovement_is_synced_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashregister",
            name="boleta_series",
            field=models.CharField(
                default="B001", help_text="Ej: B001, B002", max_length=4
            ),
        ),
        migrations.AddField(
            model_name="cashregister",
            name="factura_series",
            field=models.CharField(
                default="F001", help_text="Ej: F001, F002", max_length=4
            ),
        ),
    ]
