# Generated by Django 5.2.10 on 2026-05-23 11:21

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("cash", "0005_cashregister_boleta_series_and_more"),
        ("inventory", "0014_physicalinventory_end_date_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="cashregister",
            name="allowed_categories",
            field=models.ManyToManyField(
                blank=True,
                help_text="Selecciona qué categorías se pueden vender aquí. Si lo dejas vacío, vende todo.",
                to="inventory.category",
            ),
        ),
    ]
