# Generated by Django 5.2.10 on 2026-04-22 02:13

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="ExchangeRate",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.now,
                        unique=True,
                        verbose_name="Fecha",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(
                        auto_now_add=True, verbose_name="Fecha de Registro"
                    ),
                ),
                (
                    "buy_rate",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Compra"
                    ),
                ),
                (
                    "sell_rate",
                    models.DecimalField(
                        decimal_places=3, max_digits=5, verbose_name="Venta"
                    ),
                ),
            ],
            options={
                "verbose_name": "Historial Tipo de Cambio",
                "verbose_name_plural": "Historial Tipos de Cambio",
                "ordering": ["-created_at"],
            },
        ),
    ]
